### ISSUE TITLE
Reduce parser complexity and improving usability

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#504]
# Improving usability and reduicng parser complexity

This is an epic, which groups up the tickets regarding parser interface changes:

## Usability
- [x] [Better ways of handling errors](https://github.com/raml-org/raml-js-parser-2/issues/507)
- [x] [Create JSON schema for parser output, part1](https://github.com/raml-org/raml-js-parser-2/issues/465)
- [x] [Add RAML documentation to JSON schema](https://github.com/raml-org/raml-js-parser-2/issues/493)
- [x] [high-level should be documented better](https://github.com/raml-org/raml-js-parser-2/issues/503)
- [x] [expand array type expressions](https://github.com/raml-org/raml-js-parser-2/issues/407)

## Reducing complexity
- [x] [Reduce the number of AST layers](https://github.com/raml-org/raml-js-parser-2/issues/502)
- [x] [Implement library expansion](https://github.com/raml-org/raml-js-parser-2/issues/371)
- [x] [Introduce validation plugins](https://github.com/raml-org/raml-js-parser-2/issues/506)

# Recently done

## Usability & Reducing complexity
- [x] [Create .md description for the new API](https://github.com/raml-org/raml-js-parser-2/issues/564)
- [x] [Implement the new simplified API for JSON output](https://github.com/raml-org/raml-js-parser-2/issues/634)
- [x] [Support the new API in TCK tests](https://github.com/raml-org/raml-js-parser-2/issues/632)
- [x] [Add CI tests for the new API](https://github.com/raml-org/raml-js-parser-2/issues/633)
- [x] [Split JSON schema into several files mimicking the structure of definition system](https://github.com/raml-org/raml-js-parser-2/issues/563)
- [x] [Improve JSON Schema output from the parser](https://github.com/raml-org/raml-js-parser-2/issues/562)
- [x] Documenting new JSON changes in the new JSON schema

# What is next

## Usability
- [ ] [Documentation generation from RAML output JSON schema](https://github.com/raml-org/raml-js-parser-2/issues/492)
- [ ] [Productize the new API](https://github.com/raml-org/raml-js-parser-2/issues/683)
- [x] [Run the parser against Platform APIs](https://github.com/raml-org/raml-js-parser-2/issues/684)
- [ ] [Create the new API for high-level](https://github.com/raml-org/raml-js-parser-2/issues/685)
- [ ] [Provide md documentation for high-level methods](https://github.com/raml-org/raml-js-parser-2/issues/686)
- [ ] [Provide md documentation for high-level types](https://github.com/raml-org/raml-js-parser-2/issues/687)
- [ ] [Add hiearchy to the complex error report traces](https://github.com/raml-org/raml-js-parser-2/issues/688)

**Comment by postatum** [comment]
Closing for now as no answers. Feel free to re-open if this is still relevant.
