### ISSUE TITLE
Productize the new API

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#683]
- [x] [Create .md description for the new API](https://github.com/raml-org/raml-js-parser-2/issues/564)
- [x] [Create Getting Starting guide for the new API](https://github.com/raml-org/raml-js-parser-2/issues/724)
- [ ] [Generate html-based documentation using current new API JSON schema](https://github.com/raml-org/raml-js-parser-2/issues/725)

**Comment by postatum** [comment]
Closing for now as no answers. Feel free re-open if this is still relevant.
