### ISSUE TITLE
Epic central

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#690]
This is the central epic pointing to the other epics.

Current ones:
- [ ] [Spike on the parser performance](https://github.com/raml-org/raml-js-parser-2/issues/512)
- [ ] [Reduce parser complexity and improving usability](https://github.com/raml-org/raml-js-parser-2/issues/504)

Old ones:
- [x] [Better ways of handling errors](https://github.com/raml-org/raml-js-parser-2/issues/507)
- [x] [Introduce validation plugins](https://github.com/raml-org/raml-js-parser-2/issues/506)
- [x] [Reduce the number of AST layers](https://github.com/raml-org/raml-js-parser-2/issues/502)
- [x] [Parser size](https://github.com/raml-org/raml-js-parser-2/issues/689)

**Comment by postatum** [comment]
Closing for now as no answers. Feel free re-open if this is still relevant.
